### ISSUE TITLE
Slash Command - Self Update

### ISSUE THREAD

**Issue by gmacgre** [BYU-CS-Discord/CSBot#11]
`/pull [branch-name]` should update the bot based on the github repo. Defaults to the main branch. The bot should continue to run after the command is run (i.e. it might need a restart to get the new changes, but it shouldn't just die)

**Comment by AverageHelper** [comment]
The most popular Node.js git client I've found so far, other than using Node's CLI APIs and constructing strings from that, is [simple-git](https://www.npmjs.com/package/simple-git). IDK yet how it sanitizes strings, but at the very least we should keep user input away from the CLI wherever possible.

I like the idea of a `branch-name` parameter tho. GitHub has APIs that might let us fetch the repo's branches, and Discord has APIs for dynamic dropdown options iirc, so some combination of those would be awesome, and effectively prevent CLI injection.

**Comment by JstnMcBrd** [comment]
Closed by #68
