### ISSUE TITLE
Slash Command - xkcd search

### ISSUE THREAD

**Issue by Plyb** [BYU-CS-Discord/CSBot#16]
`/xkcd` should post a link with the most recent xkcd comic.
`/xkcd [query]` should search for xkcd comics and post the best match

Dev notes:
Perhaps look at how Ze Kaiser did this to get ideas on the search

**Comment by AverageHelper** [comment]
This one might be easiest to get feature parity. It's just a fetch and an embed, right?

**Comment by JstnMcBrd** [comment]
For the fetch, we could use the same [API](https://xkcd.vercel.app//) we use in CS 260 for the XKCD Browser lab.

**Comment by Plyb** [comment]
yeah. For this one it might be worth looking at what Ze Kaiser does and replicating that. Shouldn't be too hard. An enhancement down the line would be for it to confirm that it found the right one using an ephemeral message before posting it
