### ISSUE TITLE
Slash Command - Score Tracking

### ISSUE THREAD

**Issue by Plyb** [BYU-CS-Discord/CSBot#17]
`/track <score-name>` Begins tracking a score for the user that runs the command
`/update <score-name> <amount>` Adds `amount` to `score-name` for the issuer (can be negative or fractional)
`/list-tracking` list all of the `score-name`s being tracked for the issuer
`/stop-tracking <score-name>` erase score for the issuer on `score-name`
`/leaderboard <score-name>` show the scores of all users for `score-name` that are being tracked for `score-name`

**Comment by ZYancey** [comment]
Just for clarification this is the Highscores/Fitness Tracking correct?

**Comment by Plyb** [comment]
Correct
