### ISSUE TITLE
Simplify `CommandContext` construction

### ISSUE THREAD

**Issue by AverageHelper** [BYU-CS-Discord/CSBot#21]
@JstnMcBrd made a good point in #14 that [`handleInteraction`](https://github.com/BYU-CS-Discord/CSBot/blob/2213b7609c23e240117a1acd7b99896409a4222e/src/handleInteraction.ts#L24) is a hekkin chonker of a function.

I think that function should be in charge of constructing the context, since that's a natural part of executing a command, which is the primary job of the `handleInteraction` function. The methods (`prepareForLongRunningTasks`, `reply`, `followUp`, etc.) could be moved away, using something like a function factory, without breaking the context interface. We can't just move the functions directly, since they rely on the interaction metadata from the specific command invocation, but a factory could encapsulate the relevant logic while leaving `handleInteraction` to do the main business of constructing and dispatching the wider context.

**Comment by JstnMcBrd** [comment]
Would it be possible to make one factory that builds the entire context, and then the handler uses it? I feel like that would be simpler and reduce code duplication from multiple factories.

**Comment by AverageHelper** [comment]
It might, but as you observed, the context is *huge*, and the bulk of it is those methods. Any one factory will face a similar problem to the one we have now, of trying to define how every method will behave.

I'm not sure how much code dupe we'll get, but my hope is that it'll be negligible

**Comment by AverageHelper** [comment]
Separate factories will also simplify testing, since each unit will have only a few concerns we need to worry about

**Comment by AverageHelper** [comment]
See #25
