### ISSUE TITLE
Reaction duplication

### ISSUE THREAD

**Issue by Plyb** [BYU-CS-Discord/CSBot#24]
When users add reactions to messages, the bot will some fraction of the time, also react with that same reaction.

`/set-reaction-rate <rate> [emoji]` sets how often the bot reacts. If `emoji` is not specified, this will set the default reaction rate for all reactions, which can be overriden on a reaction-by-reaction basis by specifying `emoji`. `rate` is a simple fractional number like `0.1`. If this command has not been run yet, set the default reaction rate to `0.05`.

`/get-reaction-rate [emoji]` prints the set rate for either the default or a specific emoji. If no specific rate is set for an emoji, show the default and indicate that it is is the default.

**Comment by AverageHelper** [comment]
We should also add some command to read out the reaction rate

**Comment by JstnMcBrd** [comment]
Is there anything stopping users from spamming a reaction until the bot reacts?

**Comment by AverageHelper** [comment]
I'm sure we could design one
