### ISSUE TITLE
Decide on name/pfp for the bot

### ISSUE THREAD

**Issue by JstnMcBrd** [BYU-CS-Discord/CSBot#29]

**Comment by AverageHelper** [comment]
Bow about Botty McBotface?

**Comment by JstnMcBrd** [comment]
Honestly, I know "CS Bot" is generic and supposed to be temporary, but it's rather fitting for a CS-major-collab-project for the CS-major-Discord.

**Comment by gmacgre** [comment]
I find "CS Bot" to be a little too bland for my tastes, personally. Some good ideas have been thrown around in the discord, I say we select a number from there and let the general server decide (and then if they pick the wrong one, we can just pick what we want).
