### ISSUE TITLE
Create Basic Database Schema

### ISSUE THREAD

**Issue by AverageHelper** [BYU-CS-Discord/CSBot#32]
(Posited by @ZYancey)

Many stories (Starboard, Tracking, Smites) depend on a Database, establishing this should be a high priority as it will unlock future work
It could be nice if it regularly created snapshots of the database on a schedule or through a slash command.

**Comment by AverageHelper** [comment]
Good idea.

Have we decided yet on where and how our database will be stored? This may affect non-database agnostic things that Prisma will want to know, like how table indexes will be laid out. Some options that I've seen thrown around:

- PostgreSQL - IDK what's different with this vs other SQL offerings, could someone enlighten me?
- MySQL - runs on a server, whether locally or on another machine. [PlanetScale](https://planetscale.com/) uses this
- SQLite - stores data locally on a given file path. Performant, reliable, and zero network, nice for a small project.
- MongoDB - this and other NoSQL options usually run on a remote server, but I think MongoDB can be run on a local server without much fuss.

**Comment by AverageHelper** [comment]
[Ze Kaiser](https://github.com/ArkenStorm/Ze-Kaiser) uses [lowdb](https://www.npmjs.com/package/lowdb), which keeps everything in a JSON file on disk. This is nice for JS ergonomics, but really only viable for tiny projects with synchronous writes, not like a Discord bot with multiple concurrent users. I mention it here as an "option" only in comparison to the other serious database options out there.

**Comment by ZYancey** [comment]
My vote goes towards SQLite, Its a discord bot so I think there is merit in avoiding overcomplicating things. And a lot of the other DB options tend to be a bit heavier in my experience. If we can set up a cron job to backup the DB every so often I have no issue with the DB being stored locally on the same filesystem as the bot
