### ISSUE TITLE
Create bot account & add to dev server

### ISSUE THREAD

**Issue by AverageHelper** [BYU-CS-Discord/CSBot#5]
- who should own the bot account?

- can the bot be easily transferred between discord accounts in the future?

- how to safely distribute the token for testing purposes?

**Comment by AverageHelper** [comment]
I want to try out Discord Teams for this. Perhaps we could all "own" the bot account to some degree, or at least have access to the Discord App management console.

**Comment by JstnMcBrd** [comment]
Wouldn't that prevent the rest of us from being able to effectively test the bot on our own machines?

**Comment by Plyb** [comment]
I'm fine with that. A dev-test-prod division is pretty common in my experience
