### ISSUE TITLE
Interaction error reporting doesn't work for deferred messages

### ISSUE THREAD

**Issue by JstnMcBrd** [BYU-CS-Discord/CSBot#67]
See [this](https://discord.com/channels/1024162246491914240/1025069837149556776/1057489085050126446) conversation on Discord.
![image](https://user-images.githubusercontent.com/28303477/209904337-3a82f394-1f3b-4f04-b944-a66d607b3d00.png)

**Comment by AverageHelper** [comment]
Pretty sure the error handler just needs to check the interaction object to see if it's been deferred, and call `editReply` instead of `reply` in that case.
