### ISSUE TITLE
Slash Command - basic Help

### ISSUE THREAD

**Issue by AverageHelper** [BYU-CS-Discord/CSBot#8]
PR at #23

**Comment by AverageHelper** [comment]
I think having this one in place would give us a good base on which to build the rest.

**Comment by Plyb** [comment]
If we build this right, we shouldn't have to manually update the help text every time we add a new command. Can we structure our project in such a way that command descriptions are a necessary part of registering the command?

**Comment by AverageHelper** [comment]
Absolutely! I'm working on a branch right now to demo just that

**Comment by JstnMcBrd** [comment]
Every command file should have the name + description as long as we use the discord.js SlashCommandBuilder. It would be easy enough to load all the commands in `./commands/*.ts` and pull their names + descriptions.
