### ISSUE TITLE
/stats leaderboard errors when it can't find a user

### ISSUE THREAD

**Issue by Plyb** [BYU-CS-Discord/CSBot#92]

**Comment by Plyb** [comment]
This may be caused by a corruption in the data imported from Ze Kaiser. We could clear out the corrupted data, or we could build in some kind of more robust system to deal with unknown userids

**Comment by AverageHelper** [comment]
Anecdotally, Discord clients resolve user mentions in embeds. Since the bot is already configured to not ping anyone it mentions, we might consider foregoing the username lookup entirely, in favor of `@<${userId}>` strings.
